#!/bin/sh

scriptDir="$( dirname $( readlink -f ${BASH_SOURCE[0]} ) )/scripts"

# Standard commands, but running in containers
alias node='docker run -ti --user node -v $HOME:/home/node --workdir $( echo "$PWD" | sed "s|/home/$USER|/home/node|" ) -p 3000:3000 node:alpine node'
alias npm='docker run -ti --user node -v $HOME:/home/node --workdir $( echo "$PWD" | sed "s|/home/$USER|/home/node|" ) -p 3000:3000 node:alpine npm'

# Custom stuff
alias docker-rmi='docker rmi $(docker images --filter "dangling=true" -q --no-trunc)'
alias httpd='docker run -it --rm --name apache-httpd -p 8080:80 -v "$PWD":/usr/local/apache2/htdocs/ httpd:alpine'
alias mgit="${scriptDir}/multigit.sh"
