#!/bin/bash

# Set variables
KUBE="http://localhost:30000/api/v1/service/kube-system"
REPO="$(curl -s ${KUBE}/registry | grep clusterIP | cut -d'"' -f4)"
echo "Repo: $REPO"

# Derived variables
SCRIPT_NAME=$(basename "$0")

# Print out help text
help() {

    cat >&2 <<-EOF

    Syntax: $SCRIPT_NAME <option> [ <params> ]

    Options:

        * list          - See what is in the docker repo
        * push <image>  - Put any local docker images into the repo

EOF
}

# Print out help text and then exit
helpAndExit() {
    help
    exit 1
}

# Check syntax and get command option
[ $# -gt 0 ] || helpAndExit
COMMAND=$1
shift 1

case "$COMMAND" in

    list)
         echo "Images:"
         curl -s http://${REPO}/v2/_catalog | sed -e 's/^[^[]*//' -e 's/","/\n - /g' -e 's/^\["/ - /' -e 's/"\].*//'
        ;;

    push)
        if [[ "$1" == "" ]] ; then
            helpAndExit
        fi

        imageId=$(docker images -q $1)
        if [[ "$imageId" == "" ]] ; then
            echo "No image found: $1"
            exit 1
        fi

        docker tag $imageId ${REPO}/$1
        docker push ${REPO}/$1
        docker rmi ${REPO}/$1
        ;;

    -h | --h | -help | --help | help)
        help
        ;;

    *)
        help
        ;;

esac
